---
title: "STL Lead Inequity"
author: "Scout Leonard"
date: "8/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(here)
library(skimr)
```

```{r}

# I read the data as `stl_lead`
stl_lead <- read_delim(here::here("data", "stl_blood_lead.csv"), delim = ";") %>%
  clean_names()


```

```{r}
skimr::skim(stl_lead)

names(stl_lead)

dim(stl_lead)

summary(stl_lead)
```


## Add a New Column to a New Dataframe called `stl_lead_prop` 
```{r}
stl_lead_prop <- stl_lead %>%
  mutate(prop_white = (white / total_pop) * 100 ) %>%
  mutate(pct_elevated = str_replace(pct_elevated, 
                                    pattern = ",", 
                                    replacement = ".")) %>%
  mutate(pct_elevated = as.numeric(pct_elevated))


```

```{r}
stl_lead_plot <- ggplot(data = stl_lead_prop,
                        aes(x = pct_elevated, y = prop_white)) +
  geom_point(color = "cornflowerblue",
             alpha = 0.7) +
  labs(title = "Relationship Between Race and Elevated Blood Lead Levels",
       x = "Blood Lead Levels (%)",
       y = "Proportion of the Population Identifying as White (%)")

stl_lead_plot
```

```{r}
ggsave(here::here("figs", "snl_lead_plot.png"), height = 5, width = 6)
```

#### This scatterplot demonstrates a trend where whiter populations are associated with lower blood lead levels and vice versa. 

```{r}
stl_hist <- ggplot(data = stl_lead_prop, aes(x = pct_elevated)) +
  geom_histogram(color = "cornflowerblue", fill = "coral") +
  labs(title = "Blood Lead Levels Histogram",
       x = "Blood Lead Levels (%)",
       y = "Frequency")

stl_hist
```

```{r}
ggsave(here::here("figs", "stl_hist.jpg"), height = 6, width = 8)
```

